---
title: How to mentor at a Dojo
hero_image: images/Coderdojo_Safeguarding_Module_Social_Email_Images_V1_Email.png
description: Learn about the different roles in a CoderDojo club, mentoring styles and approaches as well as the resources available to support mentors.
version: 4
listed: false
copyedit: true
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Skills and group management
- title: Mentoring styles
- title: Supporting all learners 
- title: Reflection scenarios
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: Session resources
- title: Common programming languages
- title: Showcasing and reflection
- title: Resources for mentors
- title: More reflection scenarios
  knowledge_quiz:
    path: quiz2
    version: 1
    questions: 3
    passing_score: 3
  completion:
    - external
- title: What next?
